~~~
This is an R markdown document. It's like a markdown document, but has 
executable snippets of code that do the work (in various languages, including
bash, Python, R). It can be viewed using Rstudio---we recommend doing this.

    rstudio README.Rmd

It can also be executed (in whole) with R using the following bash snippet:*
 
    Rscript -e "rmarkdown::render('README.Rmd')"

This will compile the document into HTML while executing all the code 
snippets in the document.

This is the root document of the artifact. Start reading here.
~~~

# Introduction

This is the artifact for the paper *CodeDJ: Reproducible Queries over 
Large-Scale Software Repositories* submitted to ECOOP 2021.

## Paper details

**CodeDJ: Reproducible Queries over Large-Scale Software Repositories**

Petr Maj. CTU Prague.  
Konrad Siek. CTU Prague.  
Alexander Kovalenko. CTU Prague.   
Jan Vitek. CTU Prague and Northeastern.  

**Abstract** Analyzing massive code bases is a staple of modern software
engineering research – a welcome side-effect of the advent of large-scale
software repositories such as GitHub. Selecting projects to analyze is a
labor-intensive process that can lead to biased results if the chosen projects
are not representative. One issue is that the interface exposed by software
repositories only allows formulation of the most basic of queries. Code DJ is an
infrastructure for querying repositories composed of a persistent datastore,
constantly updated with data acquired GitHub, and an in-memory database with a
Rust query interface. Code DJ supports reproducibility, historical queries are
answered deterministically using historical states of the datastore; thus
researchers can reproduce published results. To illustrate the benefits of Code
DJ , we identify biases in the data of a published study and, by repeating the
analysis with new data, we demonstrate that its conclusions were sensitive to
the choice of projects.

## Artifact details

The paper presents a system composed of two pieces of software which are going
on display in this artifact:

- **Parasite**---a GitHub downloader and datastore,
- **Djanco**---a query engine for Parasite.

The artifact consists of the following parts:

- **Prerequisites**---a description of the packages and tools that need to be
  installed
  
> If you are using the provided VM for artifact evaluation, you can skip prerequisites as these are already provided for you. 

- **Part 1. Getting started**---a walkthrough through the setting up the 
  system from scratch, downloading a dataset, and executing queries;
- **Part 2. Case study: of bugs and languages**---a re-creation of the 
  experiment from the paper: downloading a dataset, running project selection 
  queries from the paper, performing data analysis and making the graphs from 
  the paper.

Each part is described in one or more separate Rmd documents.

| Part/Section                      |  Rmd file                                                                                  |
|:--------------------------------- | :----------------------------------------------------------------------------------------- |
| Prerequisites                     | [0-prerequisites.Rmd](0-prerequisites.Rmd)                                                 |
| Getting started                   | [1-getting-started.Rmd](1-getting-started.Rmd)                                             |
| Case-study: of bugs and languages | [2-case-study.Rmd](2-case-study.Rmd)                                                       |
|                                   | [2.1-case-study-dataset.Rmd](2.1-case-study-dataset.Rmd)                                   |
|                                   | [2.2-case-study-project-selection.Rmd](2.2-case-study-project-selection.Rmd)               |
|                                   | [2.3-case-study-data-analysis-and-graphs.Rmd](2.3-case-study-data-analysis-and-graphs.Rmd) |

We provide the results of all stages, so the reader can skip sections. In
fact there are some sections that we recommend skipping since they would
lead to downloading enormous datasets and running for multiple days. We
indicate these in the text.  

## Before we begin

In order to download projects from GitHub, our framework requires the user have a 
GitHub account and a personal access token. We cannot provide this token for you.

You can generate a token for your 
GitHub account by following the instructions 
[here](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token). 
The token does not need any scopes or permissions.

If you do not generate the token, most of the artifact will work as intended, 
however you will not be able to create any dataset on your own. We provide all 
the necessary datasets required to run the examples in the artifact.

## Directory structure

This artifact has the following directory structure:

```
codedj-ecoop-artifact
├── README.Rmd                                    # The root document. Start here.
├── 0-prerequisites.Rmd                           # Instruction for installing dependencies.
├── 1-getting-started.Rmd                         # Dataset download and query tutorial.
├── 2-case-study.Rmd                              # Reproduction of case study from the paper.
├── 2.1-case-study-dataset.Rmd                    # Case study dataset generation/download.
├── 2.2-case-study-project-selection.Rmd          # Case study project selection queries.
├── 2.3-case-study-data-analysis-and-graphs.Rmd   # Case study data analysis and graphs.
├── 3-caching-performance.Rmd                     # Caching performance experiment.
├── parasite                                      # The Parasite downloader source code.
├── djanco                                        # The Djanco query engine source code.
├── datasets                                      # Contains datasets and list of repositories to create them.
│   ├── big-dataset-repositories.csv              # List of repositories in the dataset used in the case study.
│   ├── toy-dataset-repositories.csv              # List of 10 repositories used to create the toy dataset.
│   └── predownloaded-toy-dataset                 # A toy dataset 10 repositories; used in tutorials.
├── queries                                       # Source code of crates used to run queries.
│   ├── my-query-crate                            # Query crate used in the getting started section.
│   └── paper                                     # Queries used in the paper.
├── query-results                                 # Results from executing queries.
│   ├── fse                                       # Reference results from the FSE2014 paper.
│   └── paper                                     # Query results from the experiment in the paper.
├── models                                        # Coefficients and samples generated from query-results.
├── graphs                                        # Figures generated from data analysis.
├── img                                           # Misc. images used in documents.
└── scripts                                       # Auxiliary scripts used in various analyses.
```

## Not in the artifact

We decided not to replicate the caching performance table from the paper, 
for practical reasons: 

- The difference in caching performance is only noticable in large datasets, 
  however, torturing the cache using those takes many days;
- The results are uinlikely to be replicable on other systems, since the 
  caches require large amounts of disk space and RAM to work with very large 
  datasets;
- Djanco comes pre-tuned---we would have to provide a separate version of the 
   database that caches everything.

These reasons, coupled with the fact that the table is of secondary importance 
to most readers than the remainder of the experiments, lead us to cut it from 
the artifact. 

## Not in the repository

This artifact is deposited in a [GitHub repository](https://github.com/PRL-PRG/codedj-ecoop-artifact). Due to the limitations 
of the medium, the repository does not include most of the data. This is a list of files that are already present in the artifact VM, or are generated manually by the next steps:

```
djanco
parasite
datasets/toy-dataset
datasets/dataset
query-results/paper/*.csv
```
