library(MASS)
library(readr)
library(dplyr)
library(ggplot2)
library(reticulate)


load_dataset = function(path) {
  result = read_delim(path, delim=',', escape_double=FALSE, escape_backslash=TRUE, quote="\"")
  #firstCol = colnames(result)[[1]]
  #if (substr(firstCol,1,1) == "#")
  #  colnames(result)[[1]] = substring(firstCol, 2)
  result = result %>% dplyr::select(language, project, sha, files, devs = committer, commit_date, commit_age, insertion, deletion, isbug)
  result$language = as.factor(result$language)
  invisible(result)
}


# Loads the dataset description as calculated by the dcd-describe command
#
load_dataset_description = function(path) {
  result = read_delim(path, delim=',', escape_double=FALSE, escape_backslash=TRUE, quote="\"")
  result$language = as.factor(result$language)
  result
}

load_dataset_sizes = function(path) {
  x = read_delim(path, delim=',', escape_double=FALSE, escape_backslash=TRUE, quote="\"")
  list(
      projects = as.numeric((x %>% filter(name == "projects"))$size[[1]]),
      validProjects = as.numeric((x %>% filter(name == "validProjects"))$size[[1]]),
      validCommits = as.numeric((x %>% filter(name == "validCommits"))$size[[1]]),
      validPaths = as.numeric((x %>% filter(name == "validPaths"))$size[[1]]),
      bytes = as.numeric((x %>% filter(name == "bytes"))$size[[1]])
  )
}



# Logging -----------------------------------------------------------------------------------------

# Initialzies the log and clears the data. 
#
# NOTE using this function is very dangerous if the logged data takes a lot of time to build. 
initializeLog <- function() {
  LOGFILE <<- list()
}

LOGRaw <- function(cmd, value) {
  value = format(round(value, 2), nsmall=0, big.mark=",")
  LOGFILE[cmd] <<- paste0(value, "\\xspace")
  cat(paste0(cmd, " : ", value, "\n"))
}

# Logs the given name and value. 
LOG <- function(cmd, value) {
  LOGFILE[cmd] <<- paste0(prettyNum(value), "\\xspace")
  cat(paste0(cmd, " : ", prettyNum(value), "\n"))
}

# Logs the given name and value in percentage. 
LOGPct <- function(cmd, value, max) {
  value = round((value / max) * 100, 0)
  if (value == 0)
    value = "<1"
  LOGFILE[cmd] <<- paste0(value, "\\xspace")
  cat(paste0(cmd, " : ", value, "\n"))
}

# Logs the given time
LOGTime <- function(name, value) {
  LOGFILE[name] <<- paste0(prettyTime(value), "\\xspace")
  cat(paste0(name, " : ", prettyTime(value), "\n"))
}

LOGSize <- function(name, value) {
  LOGFILE[name] <<- paste0(prettySize(value), "\\xspace")
  cat(paste0(name, " : ", prettySize(value), "\n"))
}

LOGPctAndRaw <- function(name, value, max) {
  LOGRaw(paste0(name,"Raw"), value)
  LOGPct(paste0(name,"Pct"), value, max)
  LOG(name, value);
}

LOGString <- function(cmd, value) {
  LOGFILE[cmd] <<- paste0(value, "\\xspace")
  cat(paste0(cmd, " : ", value, "\n"))
}

# Dumps the logged values to the provided file, overwriting its contents entirely
writeLog <- function(filename) {
  write("%autogenerated contents", file = filename)
  for (name in names(LOGFILE)) {
    write(paste0("\\newcommand{\\", name, "}{", LOGFILE[name], "}"), file = filename, append = TRUE)
  }
}

# Pretty printer for large numbers. Examples:
# pp(0)     -> 0
# pp(1)     -> 1
# pp(100)   -> 100
# pp(1000)   -> 1K
# pp(5200)   -> 5.2K
# pp(1000000) -> 1M
# pp(1010000) -> 1M
# pp(1100000) -> 1.1M
# pp(1000000000) -> 1B
prettyNum <- function(x, digits=2) 
  ifelse(x==0,
         paste(format(x, digits=digits, scientific=FALSE)),
         ifelse(x < 1000,
                format(x, digits=digits, scientific=FALSE),
                ifelse(x < 1000000,
                       paste(format(floor((x/1000)*10)/10, digits=digits, scientific=FALSE), "K", sep=""),
                       ifelse(x < 1000000000,
                              paste(format(floor((x/1000000)*10)/10, digits=digits, scientific=FALSE), "M", sep=""),
                              paste(format(floor((x/1000000000)*10)/10, digits=digits, scientific=FALSE), "B", sep="")))))

prettySize <- function(x, digits=2) {
  suffix = " bytes"
  if (x > 1000) {
    x = x / 1000
    suffix = "KB"
  } 
  if (x > 1000) {
    x = x / 1000
    suffix = "MB"
  } 
  if (x > 1000) {
    x = x / 1000
    suffix = "GB"
  } 
  paste0(format(x, digits = digits, scientific = FALSE), suffix)
}
  
prettyTime = function(x) {
  u = "s"
  if (x > 60) {
    x = x / 60
    u = "m"
    if (x > 60) {
      x = x / 60
      u = "h"
      if (x > 24) {
        x = x / 24
        u = "d"
        if (x > 30) {
          x = x / 30
          u = "mo"
          if (x > 12) {
            x = x / 12
            u = "y"
          }
        }
      }
    }
  }
  paste(as.integer(x), u)
}

plain <- function(x,...) {
  format(x, ..., scientific = FALSE, trim = TRUE)
}